global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'messaging-producer'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['producer:8080']

  - job_name: 'processing-consumer'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['consumer:8080']

  - job_name: 'requests-simulator'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['requests:8080']
