global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'producer'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['producer:8080']

  - job_name: 'consumer'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['consumer:8080']

  - job_name: 'requests'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['requests:8080']
