apiVersion: apps/v1
kind: Deployment
metadata:
  name: requests
spec:
  replicas: 1
  selector:
    matchLabels:
      app: requests
  template:
    metadata:
      labels:
        app: requests
    spec:
      containers:
        - name: requests
          image: microflow-simulator-requests:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080